name: rescue-link-taguig

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      DB_HOST: db
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public"
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    ports:
      - "3001:3000"
    volumes:
      - ./apps/api:/app
      - api_node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    name: rescue-link-taguig-app-network

volumes:
  api_node_modules:
  postgres_data:
