import type { Metadata } from "next";
import { inter, outfit } from "@/lib/fonts";
import { ToastProvider } from "@/providers/toast-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${outfit.variable}`}>
      <body className={inter.className} suppressHydrationWarning>
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
