name: rescue-link-taguig

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      DB_HOST: db
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public"
    command: npm run start:dev
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    name: rescue-link-taguig-app-network

volumes:
  api_node_modules:
  postgres_data:

# 1. Install frontend dependencies locally on Windows
# npm install --prefix web

# 2. Create their local frontend environment file
# echo NEXT_PUBLIC_API_URL=http://localhost:3001 > web/.env.local

# npm run dev
